### ISSUE TITLE
500 Error after installing on Redmine 3.0

### ISSUE THREAD

**Issue by shawndibble** [dkuk/ajax_counters#2]
After installing:

Completed 500 Internal Server Error in 7671ms (ActiveRecord: 515.5ms)

ActionView::Template::Error (undefined method `each' for #<ActionDispatch::Request::Session:0x00000003c78910>):
     8:   # For reduce session data length:
     9:   # c - counter, t - time, p - refresh period
    10:   cur_time = Time.now
    11:   session.each do |k,v|
    12:     if v.is_a?(Hash) && v.has_key?(:c) && v.has_key?(:t) && v.has_key?(:p)
    13:       expired = false
    14:       if v[:t]+v[:p].seconds < cur_time
  lib/redmine/hook.rb:119:in`block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in`block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in`call_hook'
  app/views/layouts/base.html.erb:14:in `_2dba6c2bce50384b466510dd84654b99'
  app/controllers/issues_controller.rb:118:in`block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'

I had to remove both this plugin and unread_issues to get the 500 error to go away and restore the site.

Environment:
  Redmine version                3.0.3.stable.14325
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  4.2.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem  
Redmine plugins:
  a_common_libs                  1.1.4
  global_roles                   2.0.0
  redmine_agile                  1.3.9
  redmine_base_deface            0.0.1
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.1
  redmine_ckeditor               1.1.0
  redmine_default_assign         0.4
  redmine_email_fetcher          0.3.1
  redmine_hotkeys_js             0.0.2
  redmine_importer               1.2.2
  redmine_issue_completion       0.0.2
  redmine_issue_status_change    1.0
  redmine_issue_templates        0.1.0
  redmine_ldap_sync              2.0.7.devel.g202f7c74b9
  redmine_monitoring_controlling 0.1.1
  redmine_multiprojects_issue    0.2
  redmine_my_page                0.1.5
  redmine_per_project_formatting 0.0.4

**Comment by dkuk** [comment]
It is old repo. It was permanently moved to https://bitbucket.org/dkuk/ajax_counters.git
